language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install 3d-connectX-env
# command to run tests
script:
  - python test/test.py
